openapi: "3.0.1"
info:
  title: "Task API"
  version: "1.0.0"
servers:
  - url: "https://XXX.execute-api.eu-central-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "test"

paths:
  /v1/tasks:
    get:
      operationId: get_tasks
      summary: Returns a list of tasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TasksResponse"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{ .GetTasksFunctionArn }}/invocations"
        type: "aws_proxy"
        passthroughBehavior: "when_no_match"

    post:
      operationId: post_tasks
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{ .PostTasksFunctionArn }}/invocations"
        type: "aws_proxy"
        passthroughBehavior: "when_no_match"

  /v1/tasks/{task_id}:
    get:
      operationId: get_task
      summary: Returns a task with the task id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "404":
          description: Not Found
    x-amazon-apigateway-integration:
      httpMethod: "POST"
      uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{ .GetTaskFunctionArn }}/invocations"
      type: "aws_proxy"
      passthroughBehavior: "when_no_match"

    put:
      operationId: put_task
      summary: Replace a task with the task id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{ .PutTaskFunctionArn }}/invocations"
        type: "aws_proxy"
        passthroughBehavior: "when_no_match"

    delete:
      operationId: delete_task
      summary: Delete a task with the task id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{ .DeleteTaskFunctionArn }}/invocations"
        type: "aws_proxy"
        passthroughBehavior: "when_no_match"

components:
  schemas:
    TaskResponse:
      properties:
        title:
          type: string
          example: Lorem ipsum dolor
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed dia
        task_id:
          type: string
          example: 4f6b3bf7-21a7-4b43-ba74-e9e442e875a2
          format: uuid
      required:
        - task_id
        - title
    TasksResponse:
      type: array
      items:
        $ref: "#/components/schemas/TaskResponse"
    TaskRequest:
      properties:
        title:
          type: string
          example: Lorem ipsum dolor
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed dia
      required:
        - title